name       : libkate
version    : 0.4.1
release    : 3
source     :
    - https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/libkate/libkate-0.4.1.tar.gz : c40e81d5866c3d4bf744e76ce0068d8f388f0e25f7e258ce0c8e76d7adc87b68
license    : BSD-3-Clause
component  :
    - multimedia.library
    - utils : multimedia.library
summary    :
    - Overlay codec for Ogg
    - utils : Tools for libkate
description: |
    Kate is an overlay codec, originally designed for karaoke and text, that can be multiplixed in Ogg. Text and images can be carried by a Kate stream, and animated. Most of the time, this would be multiplexed with audio/video to carry subtitles, song lyrics (with or without karaoke data), etc, but doesn't have to be.
patterns   :
    - utils : 
        - /usr/bin
        - /usr/lib/python*
        - /usr/share/man
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(ogg)
setup      : |
    %configure --disable-static --disable-doc
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
